# Generated by Django 3.2.9 on 2022-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220224_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
