# Generated by Django 3.2.9 on 2022-03-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Double Xtra Large')], max_length=6, null=True),
        ),
    ]
