# Generated by Django 3.2.9 on 2022-03-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
