# Generated by Django 3.2.9 on 2022-03-06 07:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhisList',
            new_name='WishList',
        ),
    ]
